# Generated by Django 4.2.6 on 2023-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Title', max_length=250),
        ),
    ]
