# Generated by Django 4.2.6 on 2023-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_myskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('turksishCV', models.FileField(upload_to='uploads/')),
                ('englishCV', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
