# Generated by Django 4.2.6 on 2023-10-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='turksishCV',
            new_name='turkishCV',
        ),
    ]
