# Generated by Django 4.2.6 on 2023-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_turksishcv_personal_turkishcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programming_languages',
            field=models.CharField(default='SQL', max_length=255),
        ),
    ]
