# Generated by Django 4.2.6 on 2023-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='englishCV',
            field=models.FileField(upload_to='uploads/cv'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='turkishCV',
            field=models.FileField(upload_to='uploads/cv'),
        ),
    ]
