# Generated by Django 4.2.6 on 2023-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_personal_github_url_personal_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='title',
            field=models.CharField(default='Title', max_length=250),
        ),
    ]
