# Generated by Django 4.2.6 on 2023-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_personal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default=False, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=True, upload_to='uploads/'),
        ),
    ]
