# Generated by Django 4.2.6 on 2023-10-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_project_image2_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
