# Generated by Django 4.2.6 on 2023-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_personal_coverletter_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_turkish',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_turkish',
            field=models.CharField(default='Turkish Title', max_length=150),
        ),
    ]
