# Generated by Django 4.2.6 on 2023-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_category_description_turkish_category_title_turkish'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_content_turkish',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_githublink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_playstorelink',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_turkish',
            field=models.CharField(default='Turkish Title', max_length=250),
        ),
    ]
