# Generated by Django 4.2.6 on 2023-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_project_project_content_turkish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_githublink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_playstorelink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
